name: php
stages:
- name: clone
  steps:
  - sourceCodeConfig:
      url: https://github.com/gitlawr/php.git
      branch: test
      branchCondition: only
- name: build
  steps:
  - runScriptConfig:
      image: php:latest
      isShell: true
      shellScript: echo hi
